# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

# install mysql2 driver on home PC:
# gem install mysql2 --platform=ruby -- '--with-mysql-lib="C:\MySQL\Connect\lib" --with-mysql-include="C:\MySQL\Connect\include"'


default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: overflow_development
  username: postgres
  password: 12345


test:
  <<: *default
  database: overflow_test
  username: postgres
  password: 12345