# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1958cc000c8fae3d4d57ed8caaa76b85063a246b3777250e04c75de3694ab7ff7a5684d4e32859ad30e0824375c3b6702deede3de0cba2bc9d5dbfa31192a5dd
  facebook_app_id: 1966592010328357
  facebook_app_secret: 66448368242062328a23195c34f32442
  twitter_app_id: 4Lffm0GiXK3XCQ5X21sWHa5Qh
  twitter_app_secret: ZmwpyCWU7Uw9bNi7cz86BIPUnrtqbzIQH0FsZPJK0VTxTNQgIl

test:
  secret_key_base: 1dd1f28bf0abab551d5c586a6c8f5ae62e91f74cc06a6a5ca34607ed3cad405f78a874b3c35bc36f2da562108a612cce8add270ad8a858ac64eec6e8dc05f76a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
